# main menu navigation
menu:
  home: /
  archives: /archives
  about: /about
  rss: /atom.xml

# Miscelaneous
favicon: /favicon.ico
logo: /logo.png

widgets:
  # - category
  # - tag
  # - tagcloud
  # - archive
  - recent_posts
  - links
links:
  - title: "GitHub"
    url: http://www.github.com/wayou
    intro: ""
  - title: "Twitter"
    url: http://www.twitter.com/liuwayong
    intro: ""

disqus_shortname: wayou
#site statistic
google_analytics: 'UA-46794744-6'

